# Config file for DeepForest pytorch module

# Cpu workers for data loaders
# Dataloaders
workers: 1
devices: auto
accelerator: auto
batch_size: 1

# Model Architecture
architecture: 'retinanet'
num_classes: 1
nms_thresh: 0.05

# Architecture specific params
retinanet:
    # Non-max supression of overlapping predictions
    score_thresh: 0.1

train:
    csv_file:
    root_dir:
    augmentations:
        - type: RandomSizedBBoxSafeCrop
          params:
            height: 300
            width: 300
            erosion_rate: 0.0
            interpolation: 1
            always_apply: False
        - type: PadIfNeeded
          params:
            always_apply: False
            p: 1.0
            min_height: 1024
            min_width: 1024
            pad_height_divisor: None
            pad_width_divisor: None
            position: "center"  # Store as string and convert in code
            border_mode: 0  # cv2.BORDER_CONSTANT as integer
            value: 0
        - type: ToTensorV2
        - type: BBox
          params:
            format: pascal_voc
            label_fields: [category_ids]

    default_augmentations:
        - type: HorizontalFlip
          params: 
            p: 0.5
        - type: VerticalFlip
          params:
            p: 0.5
        - type: RandomBrightnessContrast
          params:
            brightness_limit: 0.2
            contrast_limit: 0.2
            p: 0.5
        - type: RandomRotate90
          params:
            p: 0.5
        - type: Normalize
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            max_pixel_value: 255.0
            p: 1.0
        - type: ToTensorV2
        - type: BBox
          params:
            format: pascal_voc
            label_fields: [category_ids]
    
    # Optimizer initial learning rate
    lr: 0.001
    scheduler:
        type: 
        params:
            # Common parameters
            T_max: 10
            eta_min: 0.00001
            lr_lambda: "lambda epoch: 0.95 ** epoch"  # For lambdaLR and multiplicativeLR
            step_size: 30  # For stepLR
            gamma: 0.1  # For stepLR, multistepLR, and exponentialLR
            milestones: [50, 100]  # For multistepLR

            # ReduceLROnPlateau parameters (used if type is not explicitly mentioned)
            mode: "min"
            factor: 0.1
            patience: 10
            threshold: 0.0001
            threshold_mode: "rel"
            cooldown: 0
            min_lr: 0
            eps: 1e-08

    # Print loss every n epochs
    epochs: 1
    # Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False
    # pin images to GPU memory for fast training. This depends on GPU size and number of images.
    preload_images: False
    
validation:
    # callback args
    csv_file: 
    root_dir:
    augmentations:
    default_augmentations:
        - type: ToTensorV2
        - type: BBox
          params:
            format: pascal_voc
            label_fields: [category_ids]
    # Intersection over union evaluation
    iou_threshold: 0.4
    val_accuracy_interval: 20
